services:

  mysql:
    image: mysql:8.4
    container_name: mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

    volumes:
      - mysql-data:/var/lib/mysql

    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

    networks:
      - employee-network


  employee-app:

    build:
      context: .
      dockerfile: Dockerfile

    image: employee-app:v1
    container_name: employee-app
    restart: unless-stopped

    depends_on:
      mysql:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

    networks:
      - employee-network


  nginx:

    image: nginx:latest
    container_name: nginx
    restart: unless-stopped

    depends_on:
      - employee-app

    ports:
      - "80:80"

    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    networks:
      - employee-network


volumes:
  mysql-data:


networks:
  employee-network:
    driver: bridge
