apiVersion: v1
kind: Secret

metadata:
  name: employee-secret
  namespace: employee

type: Opaque

stringData:

  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/employee_db"

  SPRING_DATASOURCE_USERNAME: "employee_user"

  SPRING_DATASOURCE_PASSWORD: "Employee@12345"
