apiVersion: apps/v1
kind: Deployment

metadata:
  name: employee-app
  namespace: employee

spec:

  replicas: 2

  selector:
    matchLabels:
      app: employee-app

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

  template:

    metadata:
      labels:
        app: employee-app

    spec:

      containers:

        - name: employee-app

          image: ashugedekar/employee-app:6

          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8081
              protocol: TCP

          env:

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                secretKeyRef:
                  name: employee-secret
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: employee-secret
                  key: SPRING_DATASOURCE_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: employee-secret
                  key: SPRING_DATASOURCE_PASSWORD

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            failureThreshold: 30
            periodSeconds: 10
            timeoutSeconds: 2

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
