apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: employee

type: Opaque

stringData:

  MYSQL_ROOT_PASSWORD: "Root@12345"

  MYSQL_DATABASE: "employee_db"

  MYSQL_USER: "employee_user"

  MYSQL_PASSWORD: "Employee@12345"
